### ISSUE TITLE
Cannot install coc-jedi

### ISSUE THREAD

**Issue by kashewnuts** [pappasam/coc-jedi#3]
## Expected

Installed like https://github.com/pappasam/coc-jedi/releases/tag/v0.7.4

## Environment Information

 * Plugin version: https://github.com/pappasam/coc-jedi/releases/tag/v0.8.0
 * OS: macOS Catalina/Ubuntu 20.04LTS
 * Vim version: 8.2

## Provide a minimal vimrc with less than 50 lines

```vim
" minimal.vimrc
set runtimepath+=~/.cache/plugged/coc.nvim
```

## How to reproduce problems from vim startup

 1. vim -Nu minimal.vimrc
 2. `CocInstall coc-jedi`

## Upload the log file

```sh
[coc.nvim] Error on active extension coc-jedi: Error: ENOENT: no such file or directory, rmdir '~/.config/coc/extensions/node_mod
ules/coc-jedi/.venv'
    at Object.rmdirSync (fs.js:684:3)
    at createJlsVenvUnix (~/.config/coc/extensions/node_modules/coc-jedi/lib/index.js:173:22)
    at getJlsExecutableDefault (~/.config/coc/extensions/node_modules/coc-jedi/lib/index.js:195:22)
    at Object.getJlsExecutable [as default] (~/.config/coc/extensions/node_modules/coc-jedi/lib/index.js:211:16)
    at Object.activate (~/.config/coc/extensions/node_modules/coc-jedi/lib/index.js:110:50)
    at Object.activate (~/.cache/plugged/coc.nvim/build/index.js:41060:57)
    at Extensions.activate (~/.cache/plugged/coc.nvim/build/index.js:40787:19)
    at Extensions.setupActiveEvents (~/.cache/plugged/coc.nvim/build/index.js:40958:18)
    at Extensions.createExtension (~/.cache/plugged/coc.nvim/build/index.js:41129:18)
    at Extensions.loadExtension (~/.cache/plugged/coc.nvim/build/index.js:40737:18)
```

**Comment by pappasam** [comment]
I'll replace the `fs` call with `rimraf`. I'm guessing you're using an older node version than 12.10.0

**Comment by pappasam** [comment]
@kashewnuts please try the latest version and let me know if it works for you!

**Comment by kashewnuts** [comment]
That makes sense. Certainly I use "nodejs 10.x". [It is tested on "coc.nvim"](https://github.com/neoclide/coc.nvim/blob/master/.github/workflows/ci.yml#L19) and [installed on Ubuntu by apt](https://packages.ubuntu.com/focal/nodejs).

Is it possible to unify the version supported by "coc.nvim"? If that is difficult,could you please specify the supported version of "nodejs" in package.json or README?

**Comment by pappasam** [comment]
My understanding of coc is evolving with my development of this extension! Checking out its `package.json`, I should support `node>=8.10.0`. So I'll try do that from now on.

As stated above, please let me know if the latest version works for you.

**Comment by kashewnuts** [comment]
I'll give it a try.

**Comment by kashewnuts** [comment]
@pappasam It worked nodejs 12.16.3!

**Comment by pappasam** [comment]
It should hopefully also work on older versions of node as well. But I'm glad to hear it's working on node 12.16 too!

**Comment by pappasam** [comment]
I just tested with node 8.10.0 and it works fine there. Thanks for the issue, things appear to be working now!

**Comment by kashewnuts** [comment]
I have confirmed that it also works with "nodejs 10.x". Thank you very much!
